get:
  summary: List all services
  description: |
    List all services
  tags:
    - services
  operationId: listServices
  parameters:
    - in: path
      name: kadInstanceId
      schema:
        type: string
      required: true
      description: KAD instance ID
    - in: query
      name: catalog
      schema:
        type: string
      required: false
      description: Filter by catalogs (comma separated)
  responses:
    '200':
      description: List of the services
      content:
        application/json:
          schema:
            type: object
            required: [services]
            properties:
              services:
                type: array
                items:
                  $ref: '../../definition/Service.yaml'
    default:
      description: Server error
      content:
        application/json:
          schema:
            $ref: '../../definition/ServerError.yaml'

