services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443", "--health-enabled", "true"]
    env_file:
      - .env
    healthcheck:
      # https://gist.github.com/sarath-soman/5d9aec06953bbd0990c648605d4dba07
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000; echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost:9000\r\nConnection: close\r\n\r\n' >&3;cat <&3 | grep -q '\"status\": \"UP\"' && exit 0 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 12
    ports:
      - "7080:7080"
      - "7443:7443"
      - "9000:9000"

  okdp-server:
    build:
      context: .
    command: ["--config", ".local/application-local.yaml"]
    ports:
      - "$OKDP_SERVER_PORT:8090"
    env_file:
      - .env
    volumes:
      - .local:/workspace/.local
      - .go-cache/go-build:/go-build
      - .go-cache/go-mod:/go/pkg
    working_dir: /workspace
    environment:
      - OCI_USERNAME=${OCI_USERNAME}
      - OCI_PASSWORD=${OCI_PASSWORD}
      - GOCACHE=/go-build
      - GOMODCACHE=/go/pkg
    depends_on:
      keycloak:
        condition: service_healthy
    links:
      - keycloak

  # database:
  #   image: postgres:15.3-alpine
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: okdp
  #     POSTGRES_PASSWORD: okdp
  #     POSTGRES_DB: okdp
  #     POSTGRES_INITDB_ARGS: "--encoding=UTF8"
      
  swagger-ui:
    env_file:
      - .env
    image: swaggerapi/swagger-ui:v5.17.14
    ports:
      - "$SWAGGER_UI_PORT:8080"
    depends_on:
      - okdp-server

  create-clients:
      image: quay.io/keycloak/keycloak:26.0
      env_file:
       - .env
      entrypoint:
        - sh
        - .local/keycloak.sh
      restart: "no"
      depends_on:
        keycloak:
         condition: service_healthy
      working_dir: /workspace
      volumes:
        - .local:/workspace/.local
      links:
        - keycloak



