services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443", "--health-enabled", "true"]
    env_file:
      - .env
    healthcheck:
      # https://gist.github.com/sarath-soman/5d9aec06953bbd0990c648605d4dba07
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000; echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost:9000\r\nConnection: close\r\n\r\n' >&3;cat <&3 | grep -q '\"status\": \"UP\"' && exit 0 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 12
    ports:
      - "7080:7080"
      - "7443:7443"
      - "9000:9000"

  okdp-server:
    build:
      context: .
    command: ["--config", ".local/application-local.yaml"]
    ports:
      - "$OKDP_SERVER_PORT:8090"
    env_file:
      - .env
    volumes:
      - .:/workspace
      - .go-cache/go-build:/go-build
      - .go-cache/go-mod:/go/pkg
    working_dir: /workspace
    environment:
      - GOCACHE=/go-build
      - GOMODCACHE=/go/pkg
    depends_on:
      keycloak:
        condition: service_healthy
    links:
      - keycloak

  # database:
  #   image: postgres:15.3-alpine
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: okdp
  #     POSTGRES_PASSWORD: okdp
  #     POSTGRES_DB: okdp
  #     POSTGRES_INITDB_ARGS: "--encoding=UTF8"
      
  swagger-ui:
    env_file:
      - .env
    image: swaggerapi/swagger-ui:v5.17.14
    ports:
      - "$SWAGGER_UI_PORT:8080"
    depends_on:
      - okdp-server

  create-clients:
      image: quay.io/keycloak/keycloak:26.0
      env_file:
       - .env
      entrypoint:
        - sh
        - -c
        - |
           echo "Creating users, roles and clients ..."
           /opt/keycloak/bin/kcadm.sh config credentials --server http://keycloak:$KC_HOSTNAME_PORT \
              --realm master --user $KC_BOOTSTRAP_ADMIN_USERNAME --password $KC_BOOTSTRAP_ADMIN_PASSWORD

           # Users
           /opt/keycloak/bin/kcadm.sh create users -r master -s username=dev1 -s firstName=dev1 -s lastName=dev1 -s enabled=true \
             -s email=dev1.developers@example.org -s emailVerified=true
           /opt/keycloak/bin/kcadm.sh set-password -r master --username dev1 --new-password user

           /opt/keycloak/bin/kcadm.sh create users -r master -s username=adm1 -s firstName=adm1 -s lastName=adm1 -s enabled=true \
             -s email=adm1.admins@example.org -s emailVerified=true
           /opt/keycloak/bin/kcadm.sh set-password -r master --username adm1 --new-password user

           /opt/keycloak/bin/kcadm.sh create users -r master -s username=view1 -s firstName=view1 -s lastName=view1 -s enabled=true \
             -s email=view1.viewers@example.org -s emailVerified=true
           /opt/keycloak/bin/kcadm.sh set-password -r master --username view1 --new-password user

           # Create Groups
           /opt/keycloak/bin/kcadm.sh create groups -r master -s name=developers
           /opt/keycloak/bin/kcadm.sh create groups -r master -s name=viewers
           /opt/keycloak/bin/kcadm.sh create groups -r master -s name=admins

           # Create roles
           /opt/keycloak/bin/kcadm.sh create roles -r master -s name=developers
           /opt/keycloak/bin/kcadm.sh create roles -r master -s name=viewers
           /opt/keycloak/bin/kcadm.sh create roles -r master -s name=admins

           # Assign Roles to users
           /opt/keycloak/bin/kcadm.sh add-roles -r master --uusername dev1 --rolename developers
           /opt/keycloak/bin/kcadm.sh add-roles -r master --uusername view1 --rolename viewers
           /opt/keycloak/bin/kcadm.sh add-roles -r master --uusername adm1 --rolename admins

           # Create clients
           /opt/keycloak/bin/kcadm.sh create clients -r master -s clientId=public-oidc-client -s name=public-oidc-client -s publicClient=true \
                                      -s 'redirectUris=["http://localhost:8090/oauth2/callback", "http://localhost:8092/oauth2-redirect.html"]' \
                                      -s 'webOrigins=["http://localhost:8090", "http://localhost:8092"]'
           /opt/keycloak/bin/kcadm.sh create clients -r master -s clientId=confidential-oidc-client -s name=confidential-oidc-client  -s 'secret=secret1' \
                                      -s 'redirectUris=["http://localhost:8090/oauth2/callback", "http://localhost:8092/oauth2-redirect.html"]'  \
                                      -s 'webOrigins=["http://localhost:8090", "http://localhost:8092"]'
           
           echo "Update access token lifetime to 10 minutes"
           /opt/keycloak/bin/kcadm.sh update realms/master -s accessTokenLifespan=600
           echo "Users, roles and clients created successfuly"
           exit 0
      restart: "no"
      depends_on:
        keycloak:
         condition: service_healthy
      links:
        - keycloak



