// Package _compositions provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package _compositions

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BasicAuthScopes = "basicAuth.Scopes"
	Oauth2Scopes    = "oauth2.Scopes"
)

// CreateCompositionJSONBody defines parameters for CreateComposition.
type CreateCompositionJSONBody struct {
	ToDo1 string `json:"ToDo1"`
	ToDo2 string `json:"toDo2"`
	ToDo3 string `json:"toDo3"`
	ToDo4 string `json:"toDo4"`
}

// UpdateCompositionJSONBody defines parameters for UpdateComposition.
type UpdateCompositionJSONBody struct {
	ToDo1 string `json:"ToDo1"`
	ToDo2 string `json:"toDo2"`
	ToDo3 string `json:"toDo3"`
	ToDo4 string `json:"toDo4"`
}

// CreateCompositionJSONRequestBody defines body for CreateComposition for application/json ContentType.
type CreateCompositionJSONRequestBody CreateCompositionJSONBody

// UpdateCompositionJSONRequestBody defines body for UpdateComposition for application/json ContentType.
type UpdateCompositionJSONRequestBody UpdateCompositionJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all Compositions
	// (GET /spaces/{spaceId}/composition)
	ListCompositions(c *gin.Context, spaceId string)
	// Create a Compositions
	// (POST /spaces/{spaceId}/composition)
	CreateComposition(c *gin.Context, spaceId string)
	// Delete a composition
	// (DELETE /spaces/{spaceId}/composition/{compositionId})
	DeleteComposition(c *gin.Context, spaceId string, compositionId string)
	// Get a Composition by compositionId
	// (GET /spaces/{spaceId}/composition/{compositionId})
	GetCompositions(c *gin.Context, spaceId string, compositionId string)
	// Update a composition
	// (PUT /spaces/{spaceId}/composition/{compositionId})
	UpdateComposition(c *gin.Context, spaceId string, compositionId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListCompositions operation middleware
func (siw *ServerInterfaceWrapper) ListCompositions(c *gin.Context) {

	var err error

	// ------------- Path parameter "spaceId" -------------
	var spaceId string

	err = runtime.BindStyledParameterWithOptions("simple", "spaceId", c.Param("spaceId"), &spaceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter spaceId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{})

	c.Set(Oauth2Scopes, []string{"openid", "email", "profile", "roles"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListCompositions(c, spaceId)
}

// CreateComposition operation middleware
func (siw *ServerInterfaceWrapper) CreateComposition(c *gin.Context) {

	var err error

	// ------------- Path parameter "spaceId" -------------
	var spaceId string

	err = runtime.BindStyledParameterWithOptions("simple", "spaceId", c.Param("spaceId"), &spaceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter spaceId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{})

	c.Set(Oauth2Scopes, []string{"openid", "email", "profile", "roles"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.CreateComposition(c, spaceId)
}

// DeleteComposition operation middleware
func (siw *ServerInterfaceWrapper) DeleteComposition(c *gin.Context) {

	var err error

	// ------------- Path parameter "spaceId" -------------
	var spaceId string

	err = runtime.BindStyledParameterWithOptions("simple", "spaceId", c.Param("spaceId"), &spaceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter spaceId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "compositionId" -------------
	var compositionId string

	err = runtime.BindStyledParameterWithOptions("simple", "compositionId", c.Param("compositionId"), &compositionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter compositionId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{})

	c.Set(Oauth2Scopes, []string{"openid", "email", "profile", "roles"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteComposition(c, spaceId, compositionId)
}

// GetCompositions operation middleware
func (siw *ServerInterfaceWrapper) GetCompositions(c *gin.Context) {

	var err error

	// ------------- Path parameter "spaceId" -------------
	var spaceId string

	err = runtime.BindStyledParameterWithOptions("simple", "spaceId", c.Param("spaceId"), &spaceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter spaceId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "compositionId" -------------
	var compositionId string

	err = runtime.BindStyledParameterWithOptions("simple", "compositionId", c.Param("compositionId"), &compositionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter compositionId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{})

	c.Set(Oauth2Scopes, []string{"openid", "email", "profile", "roles"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetCompositions(c, spaceId, compositionId)
}

// UpdateComposition operation middleware
func (siw *ServerInterfaceWrapper) UpdateComposition(c *gin.Context) {

	var err error

	// ------------- Path parameter "spaceId" -------------
	var spaceId string

	err = runtime.BindStyledParameterWithOptions("simple", "spaceId", c.Param("spaceId"), &spaceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter spaceId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "compositionId" -------------
	var compositionId string

	err = runtime.BindStyledParameterWithOptions("simple", "compositionId", c.Param("compositionId"), &compositionId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter compositionId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{})

	c.Set(Oauth2Scopes, []string{"openid", "email", "profile", "roles"})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.UpdateComposition(c, spaceId, compositionId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/spaces/:spaceId/composition", wrapper.ListCompositions)
	router.POST(options.BaseURL+"/spaces/:spaceId/composition", wrapper.CreateComposition)
	router.DELETE(options.BaseURL+"/spaces/:spaceId/composition/:compositionId", wrapper.DeleteComposition)
	router.GET(options.BaseURL+"/spaces/:spaceId/composition/:compositionId", wrapper.GetCompositions)
	router.PUT(options.BaseURL+"/spaces/:spaceId/composition/:compositionId", wrapper.UpdateComposition)
}
