// Package _api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package _api

const (
	BasicAuthScopes = "basicAuth.Scopes"
	Oauth2Scopes    = "oauth2.Scopes"
)

// Composition defines model for Composition.
type Composition struct {
	ToDo1 string `json:"ToDo1"`
	ToDo2 string `json:"toDo2"`
	ToDo3 string `json:"toDo3"`
	ToDo4 string `json:"toDo4"`
}

// Compositions defines model for Compositions.
type Compositions struct {
	Compositions []struct {
		ToDo1 string `json:"ToDo1"`
		ToDo2 string `json:"toDo2"`
		ToDo3 string `json:"toDo3"`
		ToDo4 string `json:"toDo4"`
	} `json:"compositions"`
}

// Deployment defines model for Deployment.
type Deployment struct {
	ToDo1 string `json:"ToDo1"`
	ToDo2 string `json:"toDo2"`
	ToDo3 string `json:"toDo3"`
	ToDo4 string `json:"toDo4"`
}

// Deployments defines model for Deployments.
type Deployments struct {
	Deployments []struct {
		ToDo1 string `json:"ToDo1"`
		ToDo2 string `json:"toDo2"`
		ToDo3 string `json:"toDo3"`
		ToDo4 string `json:"toDo4"`
	} `json:"deployments"`
}

// Error defines model for Error.
type Error struct {
	Message string `json:"message"`
	Slug    string `json:"slug"`
}

// ListComponentsParams defines parameters for ListComponents.
type ListComponentsParams struct {
	// IncludeRawSpec Include or not the raw json spec
	IncludeRawSpec bool `form:"includeRawSpec" json:"includeRawSpec"`
}

// GetComponentsParams defines parameters for GetComponents.
type GetComponentsParams struct {
	// IncludeRawSpec Include or not the raw json spec
	IncludeRawSpec bool `form:"includeRawSpec" json:"includeRawSpec"`
}

// CreateSpaceJSONBody defines parameters for CreateSpace.
type CreateSpaceJSONBody struct {
	ToDo1 string `json:"ToDo1"`
	ToDo2 string `json:"toDo2"`
	ToDo3 string `json:"toDo3"`
	ToDo4 string `json:"toDo4"`
}

// UpdateSpaceJSONBody defines parameters for UpdateSpace.
type UpdateSpaceJSONBody struct {
	ToDo1 string `json:"ToDo1"`
	ToDo2 string `json:"toDo2"`
	ToDo3 string `json:"toDo3"`
	ToDo4 string `json:"toDo4"`
}

// CreateCompositionJSONBody defines parameters for CreateComposition.
type CreateCompositionJSONBody struct {
	ToDo1 string `json:"ToDo1"`
	ToDo2 string `json:"toDo2"`
	ToDo3 string `json:"toDo3"`
	ToDo4 string `json:"toDo4"`
}

// UpdateCompositionJSONBody defines parameters for UpdateComposition.
type UpdateCompositionJSONBody struct {
	ToDo1 string `json:"ToDo1"`
	ToDo2 string `json:"toDo2"`
	ToDo3 string `json:"toDo3"`
	ToDo4 string `json:"toDo4"`
}

// CreateDeploymentJSONBody defines parameters for CreateDeployment.
type CreateDeploymentJSONBody struct {
	ToDo1 string `json:"ToDo1"`
	ToDo2 string `json:"toDo2"`
	ToDo3 string `json:"toDo3"`
	ToDo4 string `json:"toDo4"`
}

// UpdateDeploymentJSONBody defines parameters for UpdateDeployment.
type UpdateDeploymentJSONBody struct {
	ToDo1 string `json:"ToDo1"`
	ToDo2 string `json:"toDo2"`
	ToDo3 string `json:"toDo3"`
	ToDo4 string `json:"toDo4"`
}

// CreateProjectsJSONBody defines parameters for CreateProjects.
type CreateProjectsJSONBody struct {
	ToDo1 string `json:"ToDo1"`
	ToDo2 string `json:"toDo2"`
	ToDo3 string `json:"toDo3"`
	ToDo4 string `json:"toDo4"`
}

// UpdateProjectJSONBody defines parameters for UpdateProject.
type UpdateProjectJSONBody struct {
	ToDo1 string `json:"ToDo1"`
	ToDo2 string `json:"toDo2"`
	ToDo3 string `json:"toDo3"`
	ToDo4 string `json:"toDo4"`
}

// CreateSpaceJSONRequestBody defines body for CreateSpace for application/json ContentType.
type CreateSpaceJSONRequestBody CreateSpaceJSONBody

// UpdateSpaceJSONRequestBody defines body for UpdateSpace for application/json ContentType.
type UpdateSpaceJSONRequestBody UpdateSpaceJSONBody

// CreateCompositionJSONRequestBody defines body for CreateComposition for application/json ContentType.
type CreateCompositionJSONRequestBody CreateCompositionJSONBody

// UpdateCompositionJSONRequestBody defines body for UpdateComposition for application/json ContentType.
type UpdateCompositionJSONRequestBody UpdateCompositionJSONBody

// CreateDeploymentJSONRequestBody defines body for CreateDeployment for application/json ContentType.
type CreateDeploymentJSONRequestBody CreateDeploymentJSONBody

// UpdateDeploymentJSONRequestBody defines body for UpdateDeployment for application/json ContentType.
type UpdateDeploymentJSONRequestBody UpdateDeploymentJSONBody

// CreateProjectsJSONRequestBody defines body for CreateProjects for application/json ContentType.
type CreateProjectsJSONRequestBody CreateProjectsJSONBody

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody UpdateProjectJSONBody
