// Package _components provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package _components

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

const (
	BasicAuthScopes = "basicAuth.Scopes"
	Oauth2Scopes    = "oauth2.Scopes"
)

// ListComponentsParams defines parameters for ListComponents.
type ListComponentsParams struct {
	// Catalog Filter by catalogs (comma separated)
	Catalog *string `form:"catalog,omitempty" json:"catalog,omitempty"`
}

// GetComponentsByNameParams defines parameters for GetComponentsByName.
type GetComponentsByNameParams struct {
	// Catalog Filter by catalogs (comma separated)
	Catalog *string `form:"catalog,omitempty" json:"catalog,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List all components
	// (GET /kad/{kadInstanceId}/components)
	ListComponents(c *gin.Context, kadInstanceId string, params ListComponentsParams)
	// Get a components by name
	// (GET /kad/{kadInstanceId}/components/{name})
	GetComponentsByName(c *gin.Context, kadInstanceId string, name string, params GetComponentsByNameParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// ListComponents operation middleware
func (siw *ServerInterfaceWrapper) ListComponents(c *gin.Context) {

	var err error

	// ------------- Path parameter "kadInstanceId" -------------
	var kadInstanceId string

	err = runtime.BindStyledParameterWithOptions("simple", "kadInstanceId", c.Param("kadInstanceId"), &kadInstanceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter kadInstanceId: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{})

	c.Set(Oauth2Scopes, []string{"openid", "email", "profile", "roles"})

	// Parameter object where we will unmarshal all parameters from the context
	var params ListComponentsParams

	// ------------- Optional query parameter "catalog" -------------

	err = runtime.BindQueryParameter("form", true, false, "catalog", c.Request.URL.Query(), &params.Catalog)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter catalog: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.ListComponents(c, kadInstanceId, params)
}

// GetComponentsByName operation middleware
func (siw *ServerInterfaceWrapper) GetComponentsByName(c *gin.Context) {

	var err error

	// ------------- Path parameter "kadInstanceId" -------------
	var kadInstanceId string

	err = runtime.BindStyledParameterWithOptions("simple", "kadInstanceId", c.Param("kadInstanceId"), &kadInstanceId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter kadInstanceId: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", c.Param("name"), &name, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter name: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BasicAuthScopes, []string{})

	c.Set(Oauth2Scopes, []string{"openid", "email", "profile", "roles"})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetComponentsByNameParams

	// ------------- Optional query parameter "catalog" -------------

	err = runtime.BindQueryParameter("form", true, false, "catalog", c.Request.URL.Query(), &params.Catalog)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter catalog: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetComponentsByName(c, kadInstanceId, name, params)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.GET(options.BaseURL+"/kad/:kadInstanceId/components", wrapper.ListComponents)
	router.GET(options.BaseURL+"/kad/:kadInstanceId/components/:name", wrapper.GetComponentsByName)
}
