openapi: "3.0.0"
info:
  version: 1.0.0
  title: OKDP Server REST Api
  description: This is a REST API reference for the OKDP Server
  contact:
    name: OKDP community
    email: idir.izitounene@kubotal.io
    url: https://okdp.io/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: OKDP documentation
  url: https://okdp.io/

servers:
  - url: /api/v1

tags:
  - name: users
    description: User profile
    externalDocs:
      url: https://github.com/okdp/okdp-server
  - name: catalogs
    description: Catalogs
    externalDocs:
      url: https://github.com/okdp/okdp-server
      
paths:
  ### Users
  /users/myprofile:
    $ref: ./paths/users/user-profile.yaml
  ### Registry Catalogs
  /catalogs:
    $ref: ./paths/catalogs/catalog-list.yaml
  /catalogs/{catalogId}:
    $ref: ./paths/catalogs/catalog-by-id.yaml
  /catalogs/{catalogId}/packages:
    $ref: ./paths/catalogs/package-list.yaml
  /catalogs/{catalogId}/packages/{name}:
    $ref: ./paths/catalogs/package-by-name.yaml
  /catalogs/{catalogId}/packages/{name}/versions:
    $ref: ./paths/catalogs/package-versions-by-name.yaml
  /catalogs/{catalogId}/packages/{name}/versions/{version}:
    $ref: ./paths/catalogs/package-definition.yaml
  /catalogs/{catalogId}/packages/{name}/versions/{version}/schema:
    $ref: ./paths/catalogs/package-schema.yaml

components:
  schemas:
    UserProfile:
      $ref: './definition/UserProfile.yaml'
    Catalog:
      $ref: './definition/Catalog.yaml'
    Package:
      $ref: './definition/Package.yaml'
    GitCommit:
      $ref: './definition/GitCommit.yaml'
    ServerError:
      $ref: './definition/ServerError.yaml'