openapi: "3.0.0"
info:
  version: 1.0.0
  title: OKDP Server REST Api
  description: This is a REST API reference for the OKDP Server
  contact:
    name: OKDP community
    email: idir.izitounene@kubotal.io
    url: https://okdp.io/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: OKDP documentation
  url: https://okdp.io/

servers:
  - url: /api/v1

tags:
  - name: users
    description: User profile
    externalDocs:
      url: https://github.com/okdp/okdp-server
  - name: kad
    description: Kad instances configuration
    externalDocs:
      url: https://github.com/okdp/okdp-server
  - name: services
    description: Services
    externalDocs:
      url: https://github.com/okdp/okdp-server
  - name: catalogs
    description: Catalogs
    externalDocs:
      url: https://github.com/okdp/okdp-server
  - name: templatereleases
    description: Template releases
    externalDocs:
      url: https://github.com/okdp/okdp-server
  - name: componentreleases
    description: Component releases
    externalDocs:
      url: https://github.com/okdp/okdp-server
  - name: components
    description: Components
    externalDocs:
      url: https://github.com/okdp/okdp-server
      
paths:
  ### Users
  /users/myprofile:
    $ref: ./paths/users/user-profile.yaml
  ### KAD instances
  /kad:
    $ref: ./paths/kad/kad-instance.yaml
  /kad/{kadInstanceId}:
    $ref: ./paths/kad/kad-instance-by-name.yaml
  ### KAD Catalog API
  /kad/{kadInstanceId}/catalogs:
    $ref: ./paths/catalogs/catalog.yaml
  /kad/{kadInstanceId}/catalogs/{name}:
    $ref: ./paths/catalogs/catalog-by-name.yaml
  ### Services API
  /kad/{kadInstanceId}/services:
    $ref: ./paths/services/service.yaml
  ### KAD Component Releases API
  /kad/{kadInstanceId}/componentreleases:
    $ref: ./paths/componentreleases/component-releases.yaml
  /kad/{kadInstanceId}/componentreleases/{name}:
    $ref: ./paths/componentreleases/component-releases-by-name.yaml
  ### KAD Template Releases API
  /kad/{kadInstanceId}/templatereleases:
    $ref: ./paths/templatereleases/template-releases.yaml
  /kad/{kadInstanceId}/templatereleases/{name}:
    $ref: ./paths/templatereleases/template-releases-by-name.yaml
  ### KAD Components API
  /kad/{kadInstanceId}/components:
    $ref: ./paths/components/component.yaml
  /kad/{kadInstanceId}/components/{name}:
    $ref: ./paths/components/component-by-name.yaml

components:
  schemas:
    UserProfile:
      $ref: './definition/UserProfile.yaml'
    Catalog:
      $ref: './definition/Catalog.yaml'
    TemplateRelease:
      $ref: './definition/TemplateRelease.yaml'
    ComponentReleasePayload:
      $ref: './definition/ComponentReleasePayload.yaml'
    ComponentReleaseRequest:
      $ref: './definition/ComponentReleaseRequest.yaml'
    ComponentReleaseResponse:
      $ref: './definition/ComponentReleaseResponse.yaml'
    Component:
      $ref: './definition/Component.yaml'
    Service:
      $ref: './definition/Service.yaml'
    FlatComponent:
      $ref: './definition/FlatComponent.yaml'
    KadInstance:
      $ref: './definition/KadInstance.yaml'
    GitCommit:
      $ref: './definition/GitCommit.yaml'
    ServerError:
      $ref: './definition/ServerError.yaml'

