openapi: "3.0.0"
info:
  version: 1.0.0
  title: OKDP Server REST Api
  description: This is a REST API reference for the OKDP Server
  contact:
    name: OKDP community
    email: idir.izitounene@kubotal.io
    url: https://okdp.io/
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
externalDocs:
  description: OKDP documentation
  url: https://okdp.io/

servers:
  - url: /api/v1

tags:
  - name: users
    description: User profile
    externalDocs:
      url: https://github.com/okdp/okdp-server
  - name: catalogs
    description: Catalogs
    externalDocs:
      url: https://github.com/okdp/okdp-server
  - name: clusters
    description: Kubernetes Clusters
    externalDocs:
      url: https://github.com/okdp/okdp-server
  - name: repositories
    description: KuboCD Git Releases
    externalDocs:
      url: https://github.com/okdp/okdp-server
  - name: k8s
    description: KuboCD K8S Releases
    externalDocs:
      url: https://github.com/okdp/okdp-server

paths:
  ### Users
  /users/myprofile:
    $ref: ./paths/users/user-profile.yaml

  ### Registry Catalogs
  /catalogs:
    $ref: ./paths/catalogs/catalog-list.yaml
  /catalogs/{catalogId}:
    $ref: ./paths/catalogs/catalog-by-id.yaml
  /catalogs/{catalogId}/packages:
    $ref: ./paths/catalogs/package-list.yaml
  /catalogs/{catalogId}/packages/{name}:
    $ref: ./paths/catalogs/package-by-name.yaml
  /catalogs/{catalogId}/packages/{name}/versions:
    $ref: ./paths/catalogs/package-versions-by-name.yaml
  /catalogs/{catalogId}/packages/{name}/versions/{version}:
    $ref: ./paths/catalogs/package-definition.yaml
  /catalogs/{catalogId}/packages/{name}/versions/{version}/schema:
    $ref: ./paths/catalogs/package-schema.yaml
  
  ### Clusters
  /clusters:
    $ref: ./paths/clusters/cluster-list.yaml
  /clusters/{clusterId}:
    $ref: ./paths/clusters/cluster-by-id.yaml
  /clusters/{clusterId}/namespaces:
    $ref: ./paths/clusters/namespace-list.yaml
  /clusters/{clusterId}/namespaces/{namespace}:
    $ref: ./paths/clusters/namespace-by-name.yaml
  
  ### Git repositories KuboCD releases
  /clusters/{clusterId}/namespaces/{namespace}/gitkustomizations:
    $ref: ./paths/repositories/repo-list.yaml
  /clusters/{clusterId}/namespaces/{namespace}/gitkustomizations/{kustomizationName}:
    $ref: ./paths/repositories/repo-by-name.yaml
  /clusters/{clusterId}/namespaces/{namespace}/gitkustomizations/{kustomizationName}/releases:
    $ref: ./paths/repositories/releases.yaml
  /clusters/{clusterId}/namespaces/{namespace}/gitkustomizations/{kustomizationName}/releases/{releaseName}:
    $ref: ./paths/repositories/release-by-name.yaml
  
  ### k8s
  /clusters/{clusterId}/namespaces/{namespace}/releases:
    $ref: ./paths/k8s/releases.yaml
  /clusters/{clusterId}/namespaces/{namespace}/releases/{releaseName}:
    $ref: ./paths/k8s/release-by-name.yaml
  /clusters/{clusterId}/namespaces/{namespace}/releases/{releaseName}/status:
    $ref: ./paths/k8s/release-status.yaml

components:
  schemas:
    UserProfile:
      $ref: './definition/UserProfile.yaml'
    Catalog:
      $ref: './definition/Catalog.yaml'
    Cluster:
      $ref: './definition/Cluster.yaml'
    Package:
      $ref: './definition/Package.yaml'
    Release:
      $ref: './definition/Release.yaml'
    ReleaseInfo:
      $ref: './definition/ReleaseInfo.yaml'
    ReleaseStatus:
      $ref: './definition/ReleaseStatus.yaml'
    GitRepository:
      $ref: './definition/GitRepository.yaml'
    GitCommit:
      $ref: './definition/GitCommit.yaml'
    ServerResponse:
      $ref: './definition/ServerResponse.yaml'

