type: object
xml:
  name: Package
required:
- "name"
- "versions"
- "repoUrl"
properties:
  name:
    type: string
    description: The name of the package
  versions:
    type: array
    items:
      type: string
    description: A list of versions for the package
  repoUrl:
    type: string
    description: The URL of OCR registry
    x-go-name: repoURL
