type: object
required: [ToDo1, toDo2, toDo3, toDo4]
properties:
  ToDo1:
    type: string
  toDo2:
    type: string
    example: toDo2
  toDo3:
    type: string
    example: toDo3
  toDo4:
    type: string
    example: "toDo4"
xml:
  name: project

