type: object
xml:
  name: Project
required:
  - name
properties:
  name:
    type: string
    example: "my-project1"
  displayName:
    type: string
    example: "My Project 1"
  environment:
    type: string
    example: "my-project1"
  description:
    type: string
    example: "my-project"
  creationTimestamp:
    type: string
    format: date-time
    readOnly: true
    example: "2025-06-12T14:00:00Z"
  status:
    type: string
    enum: ["Active", "Terminating"]
    example: "Active"
